name: APM iOS dev Build
on:
  push:
    branches:
      - ios-redesign
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  buildIPA:
    runs-on: macos-26
    name: build IPA
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: React Native Build Setup
        id: rnsetup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          env_local: ${{ secrets.ENV_LOCAL_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: 'Create env file'
        run: |
          echo "APPSTORE=true" >> .env

      - name: python fixHTTP
        run: |
          python ./scripts/release_bump.py --dev

      - name: Build IPA
        uses: ./.github/composite-actions/build-ipa

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v7
        with:
          name: APM-IPA
          path: ios/build/APM.ipa

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.GIT_BRANCH }}-build-${{ steps.rnsetup.outputs.date }}
          files: ios/build/APM.ipa
          prerelease: true
          target_commitish: ${{ env.GIT_BRANCH }}
